package interfaces;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.FuncionesJuego;
import logica.JUEGO;


public class ConfiguracionPantalla extends javax.swing.JFrame 
{   
    DefaultTableModel tablaAux = new DefaultTableModel();
    
    public ConfiguracionPantalla() 
    {
        initComponents();
        setLocationRelativeTo(null);
        setModelo();
         
        desactivaTimer();
        
        buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(botonFacil);
        buttonGroup1.add(botonIntermedio);
        buttonGroup1.add(botonDificil);
        
        buttonGroup2 = new ButtonGroup();
        buttonGroup2.add(botonSi);
        buttonGroup2.add(botonNo);
        buttonGroup2.add(botonTimer);
        
        buttonGroup3 = new ButtonGroup();
        buttonGroup3.add(botonDerecha);
        buttonGroup3.add(botonIzquierda);  
        jDesktopPane1.setForeground(Color.red);
             
    }
    
    public void setModelo()
    {
        String[] cabecera = {"Horas", "Minutos", "Segundos"};      
        tablaAux.setColumnIdentifiers(cabecera);
        tiempoLabel.setModel(tablaAux);           
    }
    public void desactivaTimer()
    {
        horas.setEnabled(false);
        min.setEnabled(false);
        sec.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonFacil = new javax.swing.JRadioButton();
        botonIntermedio = new javax.swing.JRadioButton();
        botonDificil = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tiempoLabel = new javax.swing.JTable();
        botonSi = new javax.swing.JRadioButton();
        botonIzquierda = new javax.swing.JRadioButton();
        botonNo = new javax.swing.JRadioButton();
        botonTimer = new javax.swing.JRadioButton();
        botonDerecha = new javax.swing.JRadioButton();
        Salir = new javax.swing.JButton();
        horas = new javax.swing.JTextField();
        min = new javax.swing.JTextField();
        sec = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("B) Configurar");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1. Nivel");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("2. Reloj ");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("3. Posición en la pantalla del panel de dígitos:");

        botonFacil.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        botonFacil.setForeground(new java.awt.Color(255, 255, 255));
        botonFacil.setText("Facil");
        botonFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacilActionPerformed(evt);
            }
        });

        botonIntermedio.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        botonIntermedio.setForeground(new java.awt.Color(255, 255, 255));
        botonIntermedio.setText("Intermedio");
        botonIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIntermedioActionPerformed(evt);
            }
        });

        botonDificil.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        botonDificil.setForeground(new java.awt.Color(255, 255, 255));
        botonDificil.setText("Difícil");
        botonDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDificilActionPerformed(evt);
            }
        });

        tiempoLabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Horas", "Minutos", "Segundos"
            }
        ));
        tiempoLabel.setAutoscrolls(false);
        tiempoLabel.setEditingColumn(1);
        tiempoLabel.setEditingRow(1);
        tiempoLabel.setFocusable(false);
        tiempoLabel.setOpaque(false);
        tiempoLabel.setRequestFocusEnabled(false);
        tiempoLabel.setRowHeight(40);
        tiempoLabel.setRowSelectionAllowed(false);
        tiempoLabel.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tiempoLabel.setShowVerticalLines(true);
        tiempoLabel.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tiempoLabel);

        botonSi.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        botonSi.setForeground(new java.awt.Color(255, 255, 255));
        botonSi.setText("Si");
        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });

        botonIzquierda.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        botonIzquierda.setForeground(new java.awt.Color(255, 255, 255));
        botonIzquierda.setText("Izquierda");
        botonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdaActionPerformed(evt);
            }
        });

        botonNo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        botonNo.setForeground(new java.awt.Color(255, 255, 255));
        botonNo.setText("No");
        botonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoActionPerformed(evt);
            }
        });

        botonTimer.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        botonTimer.setForeground(new java.awt.Color(255, 255, 255));
        botonTimer.setText("Timer");
        botonTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTimerActionPerformed(evt);
            }
        });

        botonDerecha.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        botonDerecha.setForeground(new java.awt.Color(255, 255, 255));
        botonDerecha.setText("Derecha");
        botonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechaActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(153, 153, 153));
        Salir.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Atras");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonFacil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonIntermedio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonDificil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonSi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonIzquierda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonTimer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonDerecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Salir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(horas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(min, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(sec, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(botonDerecha)
                                        .addGap(61, 251, Short.MAX_VALUE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(botonIzquierda)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(85, 85, 85))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonSi)
                                    .addComponent(botonNo)
                                    .addComponent(botonTimer))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonIntermedio)
                            .addComponent(botonDificil)
                            .addComponent(botonFacil))))
                .addGap(30, 329, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(botonFacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIntermedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonDificil)
                .addGap(29, 29, 29)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(botonSi)
                        .addGap(14, 14, 14)
                        .addComponent(botonNo))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonTimer)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(botonDerecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIzquierda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIntermedioActionPerformed
        JUEGO.claseJuego.setDificultad("Intermedio");  
    }//GEN-LAST:event_botonIntermedioActionPerformed

    private void botonFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacilActionPerformed
        JUEGO.claseJuego.setDificultad("Facil");  
    }//GEN-LAST:event_botonFacilActionPerformed

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        JUEGO.claseJuego.setTiempo("Si");
        desactivaTimer();
    }//GEN-LAST:event_botonSiActionPerformed

    private void botonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdaActionPerformed
        JUEGO.claseJuego.setPosicion("Izquierda");
    }//GEN-LAST:event_botonIzquierdaActionPerformed

    private void botonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoActionPerformed
        JUEGO.claseJuego.setTiempo("No");
        desactivaTimer();
    }//GEN-LAST:event_botonNoActionPerformed

    private void botonTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTimerActionPerformed
        JUEGO.claseJuego.setTiempo("Timer");
        horas.setEnabled(true);
        min.setEnabled(true);
        sec.setEnabled(true);
    }//GEN-LAST:event_botonTimerActionPerformed

    private void botonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechaActionPerformed
        JUEGO.claseJuego.setPosicion("Derecha");
    }//GEN-LAST:event_botonDerechaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
      
        if(JUEGO.claseJuego.getTiempo().equals("Timer")){
            
            if(min.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Por favor indique la cantidad de minutos");
                return;
            }

            if(sec.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Por favor indique la cantidad de segundos");
                return;
            }

            JUEGO.claseJuego.setHoras(horas.getText());
            JUEGO.claseJuego.setMin(min.getText());
            JUEGO.claseJuego.setSec(sec.getText());
        }
        

        MenuPrincipal nuevo = new MenuPrincipal();
        this.dispose();
        nuevo.setVisible(true);
        
    }//GEN-LAST:event_SalirActionPerformed

    private void botonDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDificilActionPerformed
       
        JUEGO.claseJuego.setDificultad("Dificil");
    }//GEN-LAST:event_botonDificilActionPerformed

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionPantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JRadioButton botonDerecha;
    private javax.swing.JRadioButton botonDificil;
    private javax.swing.JRadioButton botonFacil;
    private javax.swing.JRadioButton botonIntermedio;
    private javax.swing.JRadioButton botonIzquierda;
    private javax.swing.JRadioButton botonNo;
    private javax.swing.JRadioButton botonSi;
    private javax.swing.JRadioButton botonTimer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField horas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField min;
    private javax.swing.JTextField sec;
    private javax.swing.JTable tiempoLabel;
    // End of variables declaration//GEN-END:variables
}
