
package interfaces;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.util.ArrayList;
import logica.CargarPartida;
import logica.FuncionesJuego;
import logica.JUEGO;
import logica.Partida;
import logica.XML;

public class MenuPrincipal extends javax.swing.JFrame {
    
    private static XML xml = new XML();
    
    private static ArrayList<Partida> listaPartidas = xml.getPartidas();
    
    private static Partida partidaActual;
    
    public MenuPrincipal() 
    {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }
    
    public static Partida getPartidaActual(){
        
        return partidaActual;
    }
    
    // Método que retorna una partida que esté activa
    
    public static Partida getPartida(){
        
        if(JUEGO.claseJuego.getDificultad().equals("")) JUEGO.claseJuego.setDificultad("Facil");
        
        while(true){
                 
            for(Partida partida: listaPartidas){
                
                if(partida.getActivo() && JUEGO.claseJuego.getDificultad().
                        equals(partida.getNivel())){ // Si está activa la retorna

                    //System.out.println(partida.getNivel());
                    partida.setActivo(false);
                    partidaActual = partida;
                    return listaPartidas.get(2);
                }
            }      

            for(Partida partida: listaPartidas){ // Si todas están inactivas las reinicia 

                partida.setActivo(true);
            }
        }

    }
    
    public static void CargarNuevaPartida(){
        
        CargarPartida nuevo = new CargarPartida();
        
        partidaActual = nuevo.cargarPartidaXML();
        //System.out.println("EL NIVEL ES EL NIVEL " + nuevo.cargarPartidaXML().getNivel()); 
        //System.out.println(getPartidaActual().getNivel());
        
        Jugar partida = new Jugar(true);     
        partida.setVisible(true);
       
    }
    
    public static void iniciarNuevaPartida(){
        
        Jugar nuevo = new Jugar(false);     
        nuevo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuJugar = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuConfig = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Futoshiki1.png"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 102, 102)));

        menuJugar.setText("Jugar");
        menuJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuJugarMouseClicked(evt);
            }
        });
        menuJugar.add(jSeparator1);

        jMenuBar1.add(menuJugar);

        menuConfig.setText("Configuración");
        menuConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuConfigMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuConfig);

        menuAyuda.setText("Ayuda");
        menuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAyudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAyuda);

        menuAcercaDe.setText("Acerca de");
        menuAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAcercaDeMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAcercaDe);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuJugarMouseClicked
        
        Jugar nuevo = new Jugar(false);     
        this.dispose();
        nuevo.setVisible(true);
    }//GEN-LAST:event_menuJugarMouseClicked

    private void menuConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuConfigMouseClicked

        ConfiguracionPantalla nuevo = new ConfiguracionPantalla();
        this.dispose();
        nuevo.setVisible(true);
        
    }//GEN-LAST:event_menuConfigMouseClicked

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        this.dispose();
        
        
    }//GEN-LAST:event_menuSalirMouseClicked

    private void menuAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAcercaDeMouseClicked

        AcercaDe nuevo = new AcercaDe();
        this.dispose();
        nuevo.setVisible(true);
    }//GEN-LAST:event_menuAcercaDeMouseClicked

    private void menuAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAyudaMouseClicked
        // TODO add your handling code here:
        
         try
        {
            File file = new File("C:\\Users\\Admin\\OneDrive - Estudiantes ITCR\\Escritorio\\POO\\Proyecto #2\\Manual de usuario_Kendall Rodríguez Camacho_Jocsan Pérez Coto.pdf");
            if(!Desktop.isDesktopSupported())
            {
                System.out.println("No se pudo abrir");
                return;
            }
            Desktop desktop = Desktop.getDesktop();
            if(file.exists())
                desktop.open(file);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_menuAyudaMouseClicked


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenu menuJugar;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
